import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./infraestructure/context/auth-provider";

export const metadata: Metadata = {
  title: "transport Solutions S.A",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#f5f5f5]">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
